# -*- coding: utf-8 -*-
"""yapon shamlari.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18APR9EQL1jms-rk9QXxKy8tvEgRPtV8z
"""

!pip install yfinance

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

tsla = yf.Ticker("TSLA")

prices = tsla.history(interval="1d", start="2024-06-20")
prices

plt.figure()
#define witdth of the candlestick elements
width = .4
width2 = .05

#define up and down prices

up = prices[prices.Close > prices.Open]
down = prices[prices.Close < prices.Open]

#define colors to use
col2 = 'black'
col1 = 'steelblue'

#plot up prices
plt.bar(up.index,up.Close-up.Open,width,bottom=up.Open,color=col1)
plt.bar(up.index,up.High-up.Close,width2,bottom=up.Close,color=col1)
plt.bar(up.index,up.Low-up.Open,width2,bottom=up.Open,color=col1)

#plot down prices
plt.bar(down.index,down.Close-down.Open,width,bottom=down.Open,color=col2)
plt.bar(down.index,down.High-down.Open,width2,bottom=down.Open,color=col2)
plt.bar(down.index,down.Low-down.Close,width2,bottom=down.Close,color=col2)

#rotate X-axis tick labels
plt.xticks(rotation = 45, ha='right')

